%if %sysfunc(exist(WORK.'LONG'n)) %then %do;
proc sql;
    drop table WORK.'LONG'n;
run;
%end;


FILENAME REFFILE '/folders/myfolders/sasuser.v94/long.sav';

PROC IMPORT DATAFILE=REFFILE
	DBMS=SAV
	OUT=WORK.'LONG'n;
RUN;

PROC CONTENTS DATA=WORK.'LONG'n; RUN;


%web_open_table(WORK.'LONG'n);

DATA CovMatrix;
	INPUT PARM ROW COL VALUE;
	DATALINES;
	1 1 1 1
	1 2 2 1
	2 1 2 1
	3 3 3 1
	3 4 4 1
	4 3 4 1
	5 1 3 1
	5 2 4 1
	6 1 4 1
	6 2 3 1
;

/* BASIC GROWTH MODEL */

PROC MIXED COVTEST METHOD = ML DATA = LONG;
	CLASS IDYRFAM time;
	MODEL AC = age / SOLUTION DDFM=SATTERTH;
	RANDOM P1 P2 P1*age P2*age / G SUBJECT=IDYRFAM TYPE=LIN(6) 	LDATA = CovMatrix;
	REPEATED  / TYPE=CS SUBJECT=IDYRFAM*time;
RUN;

PROC MIXED COVTEST METHOD = ML DATA = LONG;
	CLASS IDYRFAM time;
	MODEL AG = age / SOLUTION DDFM=SATTERTH;
	RANDOM P1 P2 P1*age P2*age / G SUBJECT=IDYRFAM TYPE=LIN(6) 	LDATA = CovMatrix;
	REPEATED  / TYPE=CS SUBJECT=IDYRFAM*time;
RUN;

PROC MIXED COVTEST METHOD = ML DATA = LONG;
	CLASS IDYRFAM time;
	MODEL CON = age / SOLUTION DDFM=SATTERTH;
	RANDOM P1 P2 P1*age P2*age / G SUBJECT=IDYRFAM TYPE=LIN(6) 	LDATA = CovMatrix;
	REPEATED  / TYPE=CS SUBJECT=IDYRFAM*time;
RUN;

PROC MIXED COVTEST METHOD = ML DATA = LONG;
	CLASS IDYRFAM time;
	MODEL HA = age / SOLUTION DDFM=SATTERTH;
	RANDOM P1 P2 P1*age P2*age / G SUBJECT=IDYRFAM TYPE=LIN(6) 	LDATA = CovMatrix;
	REPEATED  / TYPE=CS SUBJECT=IDYRFAM*time;
RUN;

PROC MIXED COVTEST METHOD = ML DATA = LONG;
	CLASS IDYRFAM time;
	MODEL SP = age / SOLUTION DDFM=SATTERTH;
	RANDOM P1 P2 P1*age P2*age / G SUBJECT=IDYRFAM TYPE=LIN(6) 	LDATA = CovMatrix;
	REPEATED  / TYPE=CS SUBJECT=IDYRFAM*time;
RUN;

PROC MIXED COVTEST METHOD = ML DATA = LONG;
	CLASS IDYRFAM time;
	MODEL TR = age / SOLUTION DDFM=SATTERTH;
	RANDOM P1 P2 P1*age P2*age / G SUBJECT=IDYRFAM TYPE=LIN(6) 	LDATA = CovMatrix;
	REPEATED  / TYPE=CS SUBJECT=IDYRFAM*time;
RUN;